### ISSUE TITLE
PHP notices, undefined index

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/layout_wildcard#26]
I'm trying the module for the first time, and now I have a lot of PHP notices in DBlog:

> Notice: Undefined index: disabled in layout_wildcard_layout_load_by_router_item_alter() (line 26 of /my-path/modules/layout_wildcard/layout_wildcard.module).

The notices are really many, maybe they are even produced on every page.

So far, I have only one Layout where I tried to use *Layout Wildcard*. I wasn't sure if it works as expected and removed anything under "Alternative paths" in that Layout. So, I'm not sure if I'm actually using the module. However, before I remove it, I wanted to report the PHP issue.

- PHP version: 7.4.28

**Comment by indigoxela** [comment]
Very strange...

Can you check all your layout.layout.WHATEVER.json in your active config directory?

`ls -l layout.layout.*.json`

And can you also check, which one is missing the "disabled" key/setting?

`grep disabled layout.layout.*.json`

Is this a fresh Backdrop install or something older, possibly upgraded from D7?

**Comment by olafgrabienski** [comment]
Thanks for chiming in! To be honest, I had just uninstalled the module. But I have a config file backup :-)

Looking for layout.layout.*.json gives these results:

- layout.layout.admin_default.json
- layout.layout.dashboard.json
- layout.layout.default_without_sidebar.json
- layout.layout.default.json
- layout.layout.home.json

And `grep disabled layout.layout.*.json`:

- layout.layout.dashboard.json:    "disabled": false,
- layout.layout.default.json:    "disabled": false,
- layout.layout.default_without_sidebar.json:    "disabled": false,
- layout.layout.home.json:    "disabled": false,

**Comment by olafgrabienski** [comment]
> Is this a fresh Backdrop install or something older, possibly upgraded from D7?

No, not fresh at all but an upgrade from D7.

**Comment by indigoxela** [comment]
I see, the layout.layout.admin_default.json seems to be the faulty one. It's the one without a "disabled" setting.

Can you check the content of that file and possibly compare it with the default in core/modules/layout/config/layout.layout.admin_default.json?

No clue when that layout might have been damaged on your site.

**Comment by olafgrabienski** [comment]
Indeed, `"disabled": false,` is missing in that file, amongst other differences. Interestingly, it doesn't show up as overridden in the Layout list. (I don't recall if I touched the Default admin layout.)

Anyway, if I'm fine with resetting it to the defaults, would you recommend to import the JSON file for the Default admin layout from core to the site?

**Comment by indigoxela** [comment]
> Anyway, if I'm fine with resetting it to the defaults, would you recommend to import the JSON file for the Default admin layout from core to the site?

That would make sure, that the layout is 100% OK.
On the other hand, only inserting the "disabled" setting should already fix it. And then you can use the layout_wildcard module without any problems.

In theory, only saving that layout once, might also do the trick.

**Comment by olafgrabienski** [comment]
> In theory, only saving that layout once, might also do the trick.

Oh yes, that did the trick. Good to know, one more thing to check after upgrades from D7! And thanks again.

**Comment by olafgrabienski** [comment]
FTR, I just ran again in the issue with another site upgraded from Drupal 7. The file in question was again `layout.layout.admin_default.json`, and saving the Default Administrative Layout fixed the issue.

**Comment by bugfolder** [comment]
I've created a PR that (I hope) addresses this. @olafgrabienski, do you have a copy of the site you could re-run the upgrade to see if the fix covers this?

**Comment by olafgrabienski** [comment]
@bugfolder Many thanks for the PR! I have a copy of the site and I'm planning to run the upgrade again (the current upgrade is a test). I need some time before to test other things on the site and will report back as soon I do the next upgrade.

**Comment by olafgrabienski** [comment]
@bugfolder I finally run the upgrade again and could test the PR. Works for me! Steps:

- Run upgrade from D7.
- Download Layout Wildcard, and apply the PR.
- Enable the module.
- Add a Layout, and configure it.

Result: no PHP notices, yay!

PS: I checked also `layout.layout.admin_default.json`, it was still missing a "disabled" setting.

**Comment by bugfolder** [comment]
Thanks! It's merged in and cut a new release.
