### ISSUE TITLE
Invalid argument supplied for foreach() in layout_wildcard_layout_load_by_router_item_alter()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/layout_wildcard#29]
> Warning: Invalid argument supplied for foreach() in layout_wildcard_layout_load_by_router_item_alter() (line 30 of /app/modules/layout_wildcard/layout_wildcard.module).

I'm seeing this a lot in my logs. This site has "Alternative Paths" empty on a lot of layouts.

**Comment by bugfolder** [comment]
Merged. Thanks!
