### ISSUE TITLE
EntityBundleLayoutAccess->checkAccess() error

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/layout_wildcard#6]
I installed this on a site and then when I tried to create new content, I got this:

> Error: Call to a member function bundle() on string in EntityBundleLayoutAccess->checkAccess() (line 77 of /path/core/modules/layout/plugins/access/entity_bundle_layout_access.inc).

Disabling this module made things function as expected again.

**Comment by robertgarrigos** [comment]
Got the same problem :-(

**Comment by bugfolder** [comment]
I didn't experience the same problem when I tried out this module, but its code is well behind the corresponding code in 1.18. [This PR](https://github.com/backdrop-contrib/layout_wildcard/pull/7) brings the code up to date with 1.18. @Laryn, @robertgarrigos, if you could test this, the updates might have addressed the issue you experienced.

If it's still there, if you could describe enough so I can reproduce it, I'll try to debug. I'm interested in supporting and enhancing this module.

**Comment by laryn** [comment]
@bugfolder Now I'm having trouble reproducing this error. Hmm... Could have been a particular confluence of versions of Backdrop and other modules. But I'd love to put this module back in the toolbox -- thanks for working on this!

**Comment by bugfolder** [comment]
I've merged in updates that bring this code into consistency with Backdrop 1.18.x. Haven't seen further evidence of this, so I'll close this issue, but of course, if you see it again, please re-open it or post a new issue.
