### ISSUE TITLE
Request to become co-maintainer

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/layout_wildcard#8]
I would like to become a co-maintainer of this project.

**Comment by laryn** [comment]
Attn: @Gormartsen ☝️

**Comment by jenlampton** [comment]
@bugfolder Did you file a PR against the readme file, adding yourself as maintainer? (If so, can you please add a link in this issue?) I would be happy to merge your PR to make you a maintainer :)

**Comment by klonos** [comment]
I see that https://github.com/backdrop-contrib/layout_wildcard/commit/24213ea1998646854bca9403e5a117464edb66fb was merged, and proper access (admin) was granted to @bugfolder in https://github.com/backdrop-contrib/layout_wildcard/settings/access. Closing...
